# Generated by Django 3.2 on 2023-05-14 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_img_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='未诊断', max_length=20)),
                ('img', models.ImageField(default='暂无', upload_to='img')),
                ('after_img', models.TextField(default='null')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('name', models.CharField(default='暂无', max_length=100)),
                ('oc', models.CharField(default='null', max_length=20)),
                ('dr_rate', models.CharField(default='null', max_length=20)),
                ('oc_rate', models.CharField(default='null', max_length=20)),
                ('advice', models.TextField(default='暂无')),
                ('propose', models.TextField(default='暂无')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patient')),
            ],
        ),
    ]
