# Generated by Django 3.2 on 2023-05-14 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_new_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='img_type',
            new_name='dr_rate',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='rating',
            new_name='oc',
        ),
        migrations.RemoveField(
            model_name='img',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='img',
            name='advice',
            field=models.TextField(default='暂无'),
        ),
        migrations.AddField(
            model_name='img',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='img',
            name='oc_rate',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='img',
            name='state',
            field=models.CharField(default='未诊断', max_length=20),
        ),
        migrations.DeleteModel(
            name='New_img',
        ),
    ]
